name: Final-Project
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.26.4
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - requests
  - sentencepiece
  - pyarrow
  - pip
  - pip:
      - ipykernel
      - torch==2.0.1
      - transformers==4.34.0
      - datasets==2.14.5
      - accelerate==0.23.0
      - peft==0.5.0
      - bitsandbytes==0.41.1
      - rouge-score
      - wandb
      - retry_requests
      - jupyter
      - dask
      - nltk
      - sentence-transformers